# This script was generated by Antigravity to fix your deployment
Write-Host "1. Clearing old GitHub credentials..." -ForegroundColor Cyan
git credential-manager delete --host=github.com

Write-Host "2. Building the project..." -ForegroundColor Cyan
npm run build

Write-Host "3. Deploying to GitHub..." -ForegroundColor Cyan
Write-Host "(Please sign in with your 'tetycoon' account when the popup appears)" -ForegroundColor Yellow
npm run deploy

Write-Host "DONE! Your site at aitycoon.in/ai_masterclass/ should be updated in 1-2 minutes." -ForegroundColor Green
Pause
